---
format:
  html:
   page-layout: article
---

### Cloud Migration Flow Chart

::::: {.grid .column-screen-inset}

:::: {.g-col-12 .g-col-md-8}


```{ojs}
//| echo: false
last_year="2024-2025"
data_file_node="N[\\"+last_year+" data csv file\\]"
meta_file_node="M[\\"+last_year+" metadata csv file\\]"

html`<style>
:root{
--mermaid-label-fg-color: #000;
--mermaid-fg-color--lightest: #fff;
--mermaid-fg-color--lighter: #fff;
}
</style>
`

mermaid`
flowchart TD
subgraph <b></b>
  direction LR
  subgraph <i>Legend</i>
  direction LR
   L1(Data Characteristic) ~~~ L3(Decision) ~~~ L4(Data) ~~~ L5(Action)
end
subgraph <br>
  direction TB
   Z1(Cloud Migration Decision Tree) --> B{"How will<br>the data<br>be accessed?"}
   B --> Z(Individual Use Only)
   B --> E(Used for<br>analysis or Collaboration)
   Z --> C{Is the data<br>small,<br>not active?}
   E --> F{How large<br>is the data?}
   C --Yes--> D("Store in<br>Google Drive<br>(Personal Folder)")
   C --No--> F
   F --> G(Large)
   G --> I{Actively<br>worked on?}
   I --Yes-->  J{Requires<br>specific<br>application?}
   I -.No.-> L(?)
   J --Yes-->  S(Store in<br>GCP)
   S --> T(Examine<br>Privacy<br>Concerns)
   J -.No.-> L(?)
   F --> H(Moderate)
   H --> K{Actively<br>worked on?}
   K --No--> M{Requires<br>specific<br>application?}
   K -.Yes.-> R(?)
   M --No--> N{Persists<br>beyond<br>tenure?}
   M -.Yes.-> R(?)
   N --Yes--> O(Store in Google<br>Shared Drive)
   N --No--> Q("Re-evaluate Google<br>Drive (Personal Folder)")
     end
end

  classDef top fill:#fff,stroke:#4682b4,stroke-width:4px,color:#000;
  classDef htm fill:#4682b4,stroke:#333,stroke-width:2px,color:#fff;
  classDef menu fill:#ffffc5,stroke:#333,stroke-width:2px,color:#000;
  classDef data fill:#add8e6,stroke:#333,stroke-width:2px,color:#000;
  classDef action fill:#ffcccb,stroke:#333,stroke-width:2px,color:#000;
  classDef decision fill:#d4e6f9,stroke:#333,stroke-width:2px,color:#000;
  class Z1 top
  class Z,E,H,L,R,G,L1 htm
  class P,W,X,L2 menu
  class B,C,K,F,I,J,M,N,Y,L3 decision
  class V,L4 data
  class D,S,T,O,Q,L5 action
 `

```

::::

:::: {.g-col-12 .g-col-md-4 .g-row-6  style="display: grid; row-gap: 50px;"}

::: {style="background-color: #fff;padding:5px;border:solid,0px;"}

:::

::: {style="background-color: #ffffc5;padding:10px;border:solid,1px;"}

**Start:** You have data or files to store. Is the data/file for individual use only, or for analysis or collaboration with others?


:::

::: {style="background-color: #ffffc5;padding:10px;border:solid,1px;"}

**Next:** File Access

* **Is the data/file for individual use only, or for analysis or collaboration with others?**
  + Individual Use Only (e.g., work-in-progress, personal documents)
  + Analysis/Collaboration/Sharing Needed (e.g., for team analysis, broad accessibility)

:::

::: {style="background-color: #ffffc5;padding:10px;border:solid,1px;"}

**Individual Use:**

Dataset/file is very small, not actively being worked on for analysis by others, and does not require broad accessibility, or is transient work-in-progress

Store in Google Drive (Personal Folder). (Best for individual work-in-progress, personal documents, or very small datasets/files. Limited accessibility, free for standard limits, suitable for long-term preservation within these limits, but not ideal for large datasets or application-dependent data).

**Analysis/Collaboration/Sharing Needed** (e.g., for team analysis, broad accessibility)

:::

::: {style="background-color: #ffffc5;padding:10px;border:solid,1px;"}

**Size of the dataset/file:**

* Actively worked on for analysis by others, and does it require specific applications or databases to access/process it
  + Large Dataset OR Actively Worked On for Analysis by Others OR Requires Specific Applications/Databases
  + Moderate Size AND Not Actively Worked On for Analysis by Others AND Does NOT Require Specific Applications/Databases

:::

::: {style="background-color: #ffffc5;padding:10px;border:solid,1px;"}

**Privacy/accessibility requirements** (e.g., public, internal, restricted)?
Highly Restricted/Private Data OR Ultimately Intended for Broad Analytical Access: Store in Google Cloud Platform (GCP). (Essential for extremely large datasets, databases, high-performance computing, long-term archival, or integration with specific applications. Highly configurable access controls, involves direct costs, requires more technical expertise).

:::

::: {style="background-color: #ffffc5;padding:10px;border:solid,1px;"}

**Persistence**

* If the data/file needs to persist beyond an individual's tenure is for a defined team, store in a Google Shared Drive. Best for collaborative projects, data/files shared among a defined team, or data/files that need to persist beyond an individual's tenure. Controlled access, included in Google Workspace, suitable for long-term preservation, though subject to Google Drive limitations for extremely large data/files.
* If not, re-evaluate Google Drive Personal Folder or GCP



:::


::::

:::::

